### ISSUE TITLE
自动连接如果能马上生效那就好了

### ISSUE THREAD

**Issue by eaglexiang** [remmina/et-electron#1]
刚开始对 自动连接 这个选项不太理解，后来意识到如果重启程序，会自动启动连接。

我想如果选中 自动连接 时马上开启连接状态，逻辑上大概会更直观吧。:wink:

**Comment by konnyakuxzy** [comment]
@eaglexiang QwQ好的，谢谢您的建议，我我我等下有空就改（现在在在上课.jpg）

**Comment by konnyakuxzy** [comment]
已经改好啦，正在打包QwQ

**Comment by konnyakuxzy** [comment]
已经打包发布了新版啦QwQ。。。
（不是很会用Github...害怕.jpg）
