### ISSUE TITLE
覆盖安装提示一堆“无法写入”

### ISSUE THREAD

**Issue by eaglexiang** [remmina/et-electron#11]
环境：Manjaro Linux
版本：2.0.1

覆盖安装了老版，第一次打开的时候提示了一堆 `无法写入` 警告：“无法写入auto.conf”等等。

不过后续使用正常。

不知道是Bug还是正常现象？

**Comment by remmina** [comment]
感觉是 Bug，我觉得那个release应该改成“增加了新功能与一堆bug”

**Comment by eaglexiang** [comment]
问题应该已经解决
