### ISSUE TITLE
能否对内建的检查指令提供一些支持

### ISSUE THREAD

**Issue by eaglexiang** [remmina/et-electron#5]
```shell
[et.exe] ask local auth [client.conf] 可检查用户名密码是否通过检验
[et.exe] ask local ping [client.conf] 可检查对服务器的PING值
```

如果能提供对这两个指令的支持，那么在服务不能用的时候，就能轻松地判断问题出在哪里

**Comment by konnyakuxzy** [comment]
@eaglexiang 这个可以有OvO
前面三周滚回文化课没有太多时间关注跟进github，后面有时间我会做出修改的
谢谢您的建议！

**Comment by eaglexiang** [comment]
学习最重要 💯

**Comment by konnyakuxzy** [comment]
emmmm...请问大佬您认为以下哪种方式比较好呢？

1. 直接消息框显示指令信息，如"fail to ping"（较容易实现）
2. 消息框显示总结性消息，如“无法连接至服务器”（实现稍微复杂一些）

QwQ...

**Comment by eaglexiang** [comment]
我想直接显示指令的返回就好了。

更友好的总结性消息，也许用起来更舒服，但也可能造成过耦合，这对兼容性不太有利。例如目前最新的ET-Go更新到0.6，但它仍然可以和0.5内核的ET-Electron良好协同，这就是良好的兼容性。而假如你辛苦总结了目前ET指令的反馈，将来ET-Go却因为某些原因不得不做出更改，使ET-Electron相关功能失效，辛苦就白费啦。

相反，直接显示指令反馈就没有这个担忧。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: XZYQvQ<mailto:notifications@github.com>
发送时间: 2018年12月2日 21:55
收件人: konnyakuxzy/et-electron<mailto:et-electron@noreply.github.com>
抄送: Eagle Xiang<mailto:eagle.xiang@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [konnyakuxzy/et-electron] 能否对内建的检查指令提供一些支持 (#5)


emmmm...请问大佬您认为以下哪种方式比较好呢？

  1.  直接消息框显示指令信息，如"fail to ping"（较容易实现）
  2.  消息框显示总结性消息，如“无法连接至服务器”（实现稍微复杂一些）

QwQ...

―

**Comment by konnyakuxzy** [comment]
OK，这个比较好实现～今晚可能没时间搞了，系统重装了一下环境还得配置。。。
谢谢大佬的建议

**Comment by konnyakuxzy** [comment]
@eaglexiang 话说我发现ping命令在user配制不正确的时候也是fail to ping
emmm...那auth不就没有用了吗？

**Comment by eaglexiang** [comment]
AUTH主要用来检查账户配置是否正确，以及专有账户是否重复登录了。
PING主要用来检查应用层时延。User配置错误时PING的确也会报错，目前没有和网络错误区分开来，这就是未来可能会改动的地方之一呀。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: XZYQvQ<mailto:notifications@github.com>
发送时间: 2018年12月2日 22:23
收件人: konnyakuxzy/et-electron<mailto:et-electron@noreply.github.com>
抄送: Eagle Xiang<mailto:eagle.xiang@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [konnyakuxzy/et-electron] 能否对内建的检查指令提供一些支持 (#5)


@eaglexiang<https://github.com/eaglexiang> 话说我发现ping命令在user配制不正确的时候也是fail to ping
emmm...那auth不就没有用了吗？

―

**Comment by konnyakuxzy** [comment]
@eaglexiang 已经发布了v1.2.0啦，资瓷了这个功能QwQ
（对了，真的希望有空的话大佬能出一个for android版本，我现在是电脑用et.go，手机用v2ray）

**Comment by eaglexiang** [comment]
很完美，非常感谢！
Android版我下个月做吧，这个月应该没空了。

**Comment by konnyakuxzy** [comment]
233333感谢大佬Orz
其实就用空余时间做做吧，当做娱乐~反正也不急不急233333
