### ISSUE TITLE
希望更新对0.7的支持

### ISSUE THREAD

**Issue by eaglexiang** [remmina/et-electron#6]
应一位网友的issue建议，[0.7](https://github.com/eaglexiang/eagle.tunnel.go/releases/tag/v0.7)新增了对启动参数的支持。这导致现有的ET-Electron无法直接调用新版本的核心程序，过去我常做的直接更新core文件夹的做法行不通了。所以希望能跟进一下。

另外需要注意的是，Ask测试命令被取消了，替代品是Check命令，这在更新日志里有详细的说明。

多谢！祝学习顺利。

**Comment by konnyakuxzy** [comment]
@eaglexiang 好的，我今天有空就更新
其实之前就想更新啦，因为最近我发现一款特别好看的UI[argon Design](http://demo.cssmoban.com/cssthemes5/twts_83_argon/index.html)

我看到好看的UI就会手痒痒QwQ

**Comment by konnyakuxzy** [comment]
行⑧新的css写了一下午还是不会用，我还是太菜了
我还是老老实实用以前的样式吧

**Comment by eaglexiang** [comment]
@konnyakuxzy 哈哈，没关系。以前的就很漂亮。

**Comment by konnyakuxzy** [comment]
@eaglexiang 已经发布新版本（1.3.0）啦！
最大亮点可能是界面布局的美化了。。。
大佬有什么意见尽管提2333
我先去睡啦QwQ

**Comment by eaglexiang** [comment]
很完美，感谢
