### ISSUE TITLE
建议不再自带默认配置文件

### ISSUE THREAD

**Issue by eaglexiang** [remmina/et-electron#7]
每次更新的时候旧配置文件都会被覆盖，所以我们都需要手动重新配置。
是否能不再在压缩包中内置配置文件，而是在配置时再检查有无旧配置文件，没有再新建文件？

如果可以的话，希望能在以后的版本中采纳。:wink:

**Comment by eaglexiang** [comment]
如果需要ET的打包进行配合，请尽管说

**Comment by konnyakuxzy** [comment]
QAQ其实我也发现每次配置一遍比较麻烦
但是现在的打包方式只是压缩包，而不是安装包
因此配置文件都是在`./resources/app/config`
以及`./resources/app/core/config`中
如果自动检测有无旧的配置文件我暂时没有比较好的思路QAQ
倒是有一个“曲线救国”的办法：可以让et-electron导出一个类似于ssr的那个`ssr://...`这样的字符串，然后下次配制只要导入这个字符串就行了
或者您有什么比较好的建议吗？

**Comment by eaglexiang** [comment]
@konnyakuxzy 如果是ET的话应该可以将启动参数中的-c指向一个新的文件比如config/new.conf，而不是既有的client.conf。

而ETE的话，我不太清楚实现机制。不过可以把创建文件这一操作放到代码中吧。我想Electron应该有提供新建文件的函数吧

**Comment by konnyakuxzy** [comment]
@eaglexiang 嗯，新建文件之类的操作应该都可以轻松实现
问题在于：
我怎么知道旧的包安装在哪里？
目前是直接解压使用（主要是我还不会打包deb啊之类的，后面必要的话我会去研究的），因此我并不知道之前用户的安装目录，而旧的配置文件是在安装目录里的
如果是Ubuntu我比较熟悉，可以把配置文件丢在`~/config`中，这样就可以实现这个功能了
但是Windows我不是很清楚是否有这种“不用管理员权限且公用的配置文件存放目录”
QwQ请教大佬

**Comment by eaglexiang** [comment]
@konnyakuxzy 咦，我想就按照现在这样，使用相对路径就可以了吧。比如现在使用的配置文件假如为`core/config/client.conf`，就改为`core/config/new.conf`，这样可不可以呢？

**Comment by eaglexiang** [comment]
@konnyakuxzy 新建文件操作与更改旧配置文件需要的权限应该是相当的（写权限）。这应该不会引入新的权限问题才对。

**Comment by konnyakuxzy** [comment]
@eaglexiang 问题是安装新版本的时候是解压出来的一个新的文件夹啊
并不是原来那个文件夹
难道您的意思是。。。把新解压出来的文件夹黏贴覆盖过去吗？
我每次都是把原来的删了，然后把新解压出来的文件夹放过去
QAQ
可能每个人使用习惯不同
所以我觉得可以搞一个全局的那种配制文件，比如放在`~/config/et-electron`这样的系统目录下
这样使用绝对路径就可以解决问题了
后面我有时间还会再研究打包的，做成安装包而不是压缩包，应该也能解决这些问题

**Comment by eaglexiang** [comment]
@konnyakuxzy 没错，我确实都是覆盖更新的。事实上市面上的更新程序都是覆盖安装哦

**Comment by remmina** [comment]
@eaglexiang 喜迎两会，这个问题很快就会被修复了
另外由于某些原因，此项目的维护任务交给了我
（另外请问移动平台的et是咕咕咕了吗\_(:зゝ∠)\_）

**Comment by eaglexiang** [comment]
> @eaglexiang 喜迎两会，这个问题很快就会被修复了
> 另外由于某些原因，此项目的维护任务交给了我
> （另外请问移动平台的et是咕咕咕了吗_(:зゝ∠)_）

好的 :)，移动平台的ET开发目前动力不足，因为我本人使用这个办法达成了目的：[在Android中运行ET Go](https://www.eaglexiang.org/android-et-go)

**Comment by remmina** [comment]
@eaglexiang 
![image](https://user-images.githubusercontent.com/47842757/53673059-648f2180-3cc0-11e9-9805-eed6426db88f.png)
太有意思了，不过这是否说明能在arm版本上套一个简单的android外壳实现呢？
主要是完全不会安卓平台开发QwQ...

**Comment by eaglexiang** [comment]
@remmina 这个想法听起来可能可行，我还需要验证

**Comment by remmina** [comment]
@eaglexiang 新版本已经发布了，这个问题已经修复了
话说方便加一下大佬QQ吗，想认识一下大佬
如果不方便公开透露可以发邮件，我的邮箱是minaqvq@gmail.com
\_(:зゝ∠)\_

**Comment by eaglexiang** [comment]
问题已经解决
